version: '3.9'

services:
    app:
        build: .
        ports:
            -   "8000:8000"
        volumes:
            - .:/var/www/html
            - ./public/frontend:/var/www/html/public/dist
    web:
        build: .
        container_name: php-web
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_USER=root
            - DB_PASS=root
            - DB_NAME=flight_booking_system
        restart: always

    db:
        image: mariadb:10.5
        container_name: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: flight_booking_system
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: always

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:5.2.1
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - db

volumes:
    db_data:
